{% set name = "lsdeluxe" %}
{% set version = "1.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lsd-rs/lsd/archive/v{{ version }}.tar.gz
  sha256: 120935c7e98f9b64488fde39987154a6a5b2236cb65ae847917012adf5e122d1

build:
  number: 1
  ignore_run_exports_from:
    # we want to ignore libstdcxx, but not libgcc; the latter also comes in through
    # compiler('c'), and conda keeps that despite ignoring the cxx run-exports
    - {{ compiler('cxx') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  # [linux]
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - lsd --help

outputs:
  - name: {{ name }}
  - name: lsd-rs

about:
  home: https://github.com/lsd-rs/lsd
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: The next gen ls command
  dev_url: https://github.com/lsd-rs/lsd

extra:
  recipe-maintainers:
    - m-rossi
